### ISSUE TITLE
Login to connect portal (with or without account) remove boundless plugin repo url

### ISSUE THREAD

**Issue by luipir** [boundlessgeo/qgis-connect-plugin#3] opened 2016-09-08 16:33 UTC
tested with b27 and b31 on win7

after connect usign connect plugin (I don't know if I'm able to connect or not, but I used my connect portal working credentials), the plugin manager is opened, but fail to connect to bioundless plugin repo and the URL is set to "".

The url is set correctly just before to run connect plugin.

**Comment by luipir** [comment] 2016-09-08 16:45
hard to determine the fail the behaviour... my test procedure is:

1) open qgis (in a clean installation) on the clean win env
2) open plugin manager to check that urls are correct
3) connect with connect plugin (using my working connect portal account or with wrong credential)
4) the opened plugin manager does not have URL set for boundless plugin manager

if I retry to connect with connect plugin, the url is then set correctly!

**Comment by luipir** [comment] 2016-09-08 17:06
confirmed bug also on win10 with another working connect portal account

I should add that after added connect credentials, the configured repo are not re-loaded and they result "Non connected".... I don't know if it is the expected behaviour.

**Comment by alexbruy** [comment] 2016-09-08 17:51
Hmm, am I right that your clean environment already has boundless repo added to QGIS settings? Because usually the only repo added to Plugin Manager is official repo. Connect added Boundless repo only after accepting (pressing "Login" button) dialog.

I'm looking at it now and trying to reproduce.

**Comment by alexbruy** [comment] 2016-09-08 18:15
I think I found issue. Working on fix now

**Comment by luipir** [comment] 2016-09-08 21:41
please trigger @dakcarto when it is fixed, I suppose we would trigger a new build, As far as I well remember a trigger would be automatically fired, but better ask to avoid package something not aligned.

about "your clean environment already has boundless repo added to QGIS settings" yes, the repo is available after clean istall and start qgis (just closing connect plugin when it start first time).

**Comment by dakcarto** [comment] 2016-09-08 23:04
> about "your clean environment already has boundless repo added to QGIS settings" yes, the repo is available after clean istall and start qgis (just closing connect plugin when it start first time).

Correct. This is added by the NSIS installer script, independent of Connect plugin.

**Comment by alexbruy** [comment] 2016-09-09 05:36
Should be fixed now.

**Closed** 2016-09-09 05:36 UTC
Labels: bug

**Comment by luipir** [comment] 2016-09-09 13:10
tested on win7... BD1.0_b34 installing Connect dev version => no issue!
