### ISSUE TITLE
Failing automated tests in Tester plugin for Connect as shipped with b5 installer of BD

### ISSUE THREAD

**Issue by gioman** [boundlessgeo/qgis-connect-plugin#24] opened 2017-06-25 17:26 UTC
Windows 7 (most certainly also Windows 10, will confirm)
Boundless-Desktop-1.1.0-x64_RC_b5.exe 
tester plugin: 0.1-201701020817-DE65150
plugin: as shipped with Boundless-Desktop-1.1.0-x64_RC_b5.exe

Report attached.
[connect_25062017_automated_win7_b5installer.html.zip](https://github.com/boundlessgeo/qgis-connect-plugin/files/1100490/connect_25062017_automated_win7_b5installer.html.zip)

**Comment by volaya** [comment] 2017-06-25 17:40
@alexbruy I will take care of this

**Comment by gioman** [comment] 2017-06-25 19:56
Same failures on Win 10.

**Comment by alexbruy** [comment] 2017-06-26 09:14
Fixed

**Comment by gioman** [comment] 2017-06-26 10:03
now using Connect in the DEV repo

```
TypeError: 'NoneType' object is not callable 
Traceback (most recent call last):
  File "C:/Users/boundless/.qgis2/python/plugins\qgistester\plugin.py", line 65, in test
  File "C:/Users/boundless/.qgis2/python/plugins\qgistester\testerwidget.py", line 72, in startTesting
  File "C:/Users/boundless/.qgis2/python/plugins\qgistester\testerwidget.py", line 87, in runNextTest
  File "C:/Users/boundless/.qgis2/python/plugins\qgistester\testerwidget.py", line 122, in runNextStep
TypeError: 'NoneType' object is not callable
```


and the tester plugin folder gets deleted from file system.
[connect_auomated_tests_problems.mp4.zip](https://github.com/boundlessgeo/qgis-connect-plugin/files/1101727/connect_auomated_tests_problems.mp4.zip)

**Comment by volaya** [comment] 2017-06-26 11:43
@alexbruy I am not able to reproduce it, but i guess that the issue might be here:

https://github.com/boundlessgeo/qgis-connect-plugin/blob/master/boundlessconnect/tests/testerplugin.py#L272

Any reason why we should use this method and not just delete the folder with shutil.rmtree? Just to try, it might fix the problem. Although i dont really see why it might be happening...

**Comment by alexbruy** [comment] 2017-06-26 11:52
Function `removeDir` is from QGIS Plugin Manager and it can handle both normal directories and symlinks. Let me try to reproduce and debug it.

**Comment by alexbruy** [comment] 2017-06-26 12:09
Should be fixed

**Closed** 2017-06-26 15:51 UTC
Labels: bug
