### ISSUE TITLE
python error when trying to add basemaps to default project

### ISSUE THREAD

**Issue by gioman** [boundlessgeo/qgis-connect-plugin#28] opened 2017-06-25 19:09 UTC
The first click in "add to default project" in a result of a search for basemaps works as expected, any following one produce a python error, this also after restarting qgis and re-logging in Connect.

plugin: as shipped with Boundless-Desktop-1.1.0-x64_RC_b5.exe

```
IOError: [Errno 22] invalid mode ('wb') or filename: u'C:/Users/boundless/.qgis2//project_default-2017-06-25-20:06:51.qgs' 
Traceback (most recent call last):
  File "C:/PROGRA~1/BOUNDL~1/Desktop/1.1/osgeo4w/apps/qgis/./python/plugins\boundlessconnect\gui\connectdockwidget.py", line 183, in linkClicked
    content.addToDefaultProject(self.roles)
  File "C:/PROGRA~1/BOUNDL~1/Desktop/1.1/osgeo4w/apps/qgis/./python/plugins\boundlessconnect\connect.py", line 320, in addToDefaultProject
    if not basemaputils.createOrAddDefaultBasemap([self.json], [self.name], authId):
  File "C:/PROGRA~1/BOUNDL~1/Desktop/1.1/osgeo4w/apps/qgis/./python/plugins\boundlessconnect\basemaputils.py", line 227, in createOrAddDefaultBasemap
    return addToDefaultProject(maps, visibleMaps, authcfg)
  File "C:/PROGRA~1/BOUNDL~1/Desktop/1.1/osgeo4w/apps/qgis/./python/plugins\boundlessconnect\basemaputils.py", line 99, in addToDefaultProject
    shutil.copy2(defaultProjectPath(), backup)
  File "C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\apps\Python27\lib\shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "C:\PROGRA~1\BOUNDL~1\Desktop\1.1\osgeo4w\apps\Python27\lib\shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 22] invalid mode ('wb') or filename: u'C:/Users/boundless/.qgis2//project_default-2017-06-25-20:06:51.qgs'
```

**Comment by gioman** [comment] 2017-06-25 20:00
Same problem on Windows 10.

**Comment by volaya** [comment] 2017-06-25 20:06
looks like the problem is with the colon in the name. That's not a valid character for windows filenames. Should be easy to fix. I will take care of it

**Comment by volaya** [comment] 2017-06-26 06:47
should be fixed, please re-test

**Closed** 2017-06-26 15:42 UTC
Labels: bug
